server:
  port: 8204

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://127.0.0.1:8858
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6380
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
#阿里云 短信
aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI0YbQf3pX8WqC
    secret: jX8D04DmDI3gGKjW5kaFYSzugfqmmT
